name: "deploy secuencial en github"

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    env:
      NAME: odon
    steps:
      - name: Hola mundo
        run: echo "Hola mundo $NAME"

  second-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo segundo"
