name: "deploy secuencial en github"

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    env:
      NAME: odon
    steps:
      - name: Hola mundo
        run: echo "Hola mundo $NAME"

      - name: working dir
        run: ls -al

      - name: action
        uses: actions/checkout@v4

      - name: working dir after action
        run: ls -al

  second-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo segundo"

  tercy-job:
    runs-on: ubuntu-latest
    steps:
      - name: working outputs
        id: step-outputs
        run: echo "my_variable=hola a todos" >> $GITHUB_OUTPUT

      - name: get outputs
        run: echo ${{steps.step-outputs.outputs.my_variable}}
