name: "Deploy github actions"

on:
  push:
    branches: ["main-one"]

jobs:
  deploy-github-actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hacemos pull del codigo"
      - run: echo "Correr migraciones"
      - run: echo "Generar binarios"
      - run: echo "Publicar Versiones"
